baseURL = "http://jean85.github.io/"
languageCode = "en-us"
title = "Alessandro Lai"
theme = "mainroad"
# googleAnalytics = "UA-XXXXXXXX-X"       # Google Analytics UA number

[Author] # Used in authorbox
  name = "Alessandro Lai"
  bio = "Lead project developer at Facile.it, PHP-FIG secretary, PHP UG Milano coordinator"
  avatar = "images/avatar-alessandro-lai.jpg"

[Params]
  author = "Alessandro Lai"
  logo = "images/avatar-alessandro-lai.jpg"
  description = "Personal blog, slide storage, rant box"
  paginate = 5
  authorbox = true
  twitter_cards = true
  readmore = true
  post_navigation = true
  postSections = ["post", "release"]

  # Publisher
  ## adsensePublisher = "ca-pub-XXX"    # Required if you want to include Google Adsense
  adsenseSlot = "XXX"                   # Required slot to display ads
  adsenseSlotSticky = "XXX"             # Enables sticky ads feature, value maybe the same with adsenseSlot, remove if you don't want display sticky ads

  # SEO configs
  seotitle = "Hugo Blog Title (SEO Version)"
  googleSiteVerification = "google_site_verification_code"    # Google Webmaster
  msValidate = "bing_site_verification_code"                  # Bing Webmaster

  # Social networks
  email = "name@domain.com"
  github = "huyb1991"
  twitter = "twitter_username"
  linkedin = "linkedin_username"
  facebook = "facebook_username"
  google = "googleplus_id_number"
  instagram = "instagram_username"
  youtube = "youtube_username"
  dribbble = "dribbble_username"

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "right"  # Configure layout for list pages
  single = "right" # Configure layout for single pages
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget (disabled by default)

[Params.widgets.social]
  # Enable parts of social widget
  facebook = "username"
  twitter = "username"
  instagram = "username"
  linkedin = "username"
  telegram = "username"
  github = "username"
  gitlab = "username"
  email = "example@example.com"

[taxonomies]
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = "Who am I"
  weight = 1
  identifier = "who-am-i"
  url = "/who-am-i/"
[[menu.main]]
  name = "Blog"
  weight = 10
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "Slides"
  weight = 20
  url = "/slides/"
[[menu.main]]
  name = "Categories"
  weight = 30
  identifier = "categories"
  url = "/categories/"
[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"
